INSERT INTO PHONE_NUMBER_DETAILS (PHONE_NUMBER, PHONE_NUMBER_TYPE, PHONE_NUMBER_STATUS, IS_ACTIVE, CREATED_DATE_TIME, UPDATED_DATE_TIME)
VALUES
    ('0412345671', 'MOBILE', 'ASSIGNED', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345672', 'WORK', 'ASSIGNED', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345673', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345674', 'MOBILE', 'ASSIGNED', TRUE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345675', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345676', 'MOBILE', 'ASSIGNED', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345677', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345678', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345679', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345680', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345681', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345682', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345683', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345684', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345685', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345686', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345687', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345688', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345689', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345690', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345691', NULL, 'AVAILABLE', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345692', NULL, 'DORMANT', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345693', NULL, 'DORMANT', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345694', NULL, 'DORMANT', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),
    ('0412345695', NULL, 'DORMANT', FALSE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_NAME, CUSTOMER_EMAIL_ID)
VALUES
    ('John Doe', 'john@example.com'),
    ('Jane Citizen', 'jane@example.com'),
    ('Ruby Sky', 'ruby@example.com'),
    ('David Earth', 'david@example.com'),
    ('Will Rome', 'will.rome@example.com');

INSERT INTO CUSTOMER_PHONE_MAPPING (CUSTOMER_DETAILS_ID, PHONE_NUMBER_DETAILS_ID)
VALUES
    (1, 1),
    (1, 2),
    (2, 4),
    (3, 6);