CREATE TABLE PHONE_NUMBER_DETAILS
(
    PHONE_NUMBER_DETAILS_ID     BIGINT AUTO_INCREMENT PRIMARY KEY,
    PHONE_NUMBER        VARCHAR(20),
    PHONE_NUMBER_TYPE   VARCHAR(50),
    PHONE_NUMBER_STATUS VARCHAR(50),
    IS_ACTIVE           BOOLEAN,
    CREATED_DATE_TIME   TIMESTAMP,
    UPDATED_DATE_TIME   TIMESTAMP
);

CREATE TABLE CUSTOMER_DETAILS
(
    CUSTOMER_DETAILS_ID       BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME     VARCHAR(100),
    CUSTOMER_EMAIL_ID VARCHAR(100),
    CREATED_DATE_TIME   TIMESTAMP,
    UPDATED_DATE_TIME   TIMESTAMP
);

CREATE TABLE CUSTOMER_PHONE_MAPPING
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_DETAILS_ID BIGINT,
    PHONE_NUMBER_DETAILS_ID    BIGINT,
    CREATED_DATE_TIME   TIMESTAMP,
    UPDATED_DATE_TIME   TIMESTAMP,
    CONSTRAINT FK_CUSTOMER_PRODUCTS_CUSTOMER
        FOREIGN KEY (CUSTOMER_DETAILS_ID) REFERENCES CUSTOMER_DETAILS (CUSTOMER_DETAILS_ID),
    CONSTRAINT FK_CUSTOMER_PRODUCTS_PHONE
        FOREIGN KEY (PHONE_NUMBER_DETAILS_ID) REFERENCES PHONE_NUMBER_DETAILS (PHONE_NUMBER_DETAILS_ID)
);