CREATE TABLE PHONE_NUMBER_DETAILS
(
    PHONE_NUMBER_DETAILS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PHONE_NUMBER            VARCHAR(20) NOT NULL ,
    PHONE_NUMBER_TYPE       VARCHAR(50),
    PHONE_NUMBER_STATUS     VARCHAR(50) NOT NULL ,
    IS_ACTIVE               BOOLEAN,
    CREATED_DATE_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_PHONE_NUMBER UNIQUE (PHONE_NUMBER)
);

CREATE TABLE CUSTOMER_DETAILS
(
    CUSTOMER_DETAILS_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME       VARCHAR(100) NOT NULL ,
    CUSTOMER_EMAIL_ID   VARCHAR(100) NOT NULL ,
    CREATED_DATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_CUSTOMER_NAME_EMAIL UNIQUE (CUSTOMER_NAME, CUSTOMER_EMAIL_ID)
);

CREATE TABLE CUSTOMER_PHONE_MAPPING
(
    ID                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_DETAILS_ID     BIGINT,
    PHONE_NUMBER_DETAILS_ID BIGINT,
    CREATED_DATE_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CUSTOMER_PRODUCTS_CUSTOMER
        FOREIGN KEY (CUSTOMER_DETAILS_ID) REFERENCES CUSTOMER_DETAILS (CUSTOMER_DETAILS_ID),
    CONSTRAINT FK_CUSTOMER_PRODUCTS_PHONE
        FOREIGN KEY (PHONE_NUMBER_DETAILS_ID) REFERENCES PHONE_NUMBER_DETAILS (PHONE_NUMBER_DETAILS_ID)
);